name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  jose: ^0.3.1
  http: ^1.2.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
